export * from './copa-grupo.controller';
export * from './copa-pais-sede.controller';
export * from './copa.controller';
export * from './equipo-grupo.controller';
export * from './equipo.controller';
export * from './grupo-copa.controller';
export * from './grupo-equipo.controller';
export * from './grupo.controller';
export * from './pais-persona.controller';
export * from './pais-sede-copa.controller';
export * from './pais-sede-pais.controller';
export * from './pais-sede.controller';
export * from './pais.controller';
export * from './persona-pais.controller';
export * from './persona-tecnico.controller';
export * from './persona.controller';
export * from './ping.controller';
export * from './tecnico.controller';

